package ee.svekko.eventmgr.error;

public enum ApiError {
    EVENT_WITH_SUCH_TITLE_ALREADY_EXISTS,
    EVENT_NOT_FOUND,
    EVENT_NO_FREE_SPOTS_LEFT,
    EVENT_PERSON_ALREADY_ENROLLED,
    EVENT_DATE_ALREADY_IN_PAST,
    UNAUTHORIZED,
    INVALID_ID_CODE
}
